[anime-shaders]
profile-desc=Anime only (line art + clean gradients)
profile-cond=(p.width==1920 and p.width==1080) and p.estimated-vf-fps == 24
scale=ewa_lanczossharp
cscale=spline64
dscale=spline64
scale-antiring=0.6
scale-radius=3.142857
#scale-blur=1.05
dither-depth=auto
dither=fruit
deband=yes
deband-iterations=2
deband-threshold=64
deband-range=24
deband-grain=4
profile-restore=copy
on-loaded=script-message set-var active_profile anime-shaders
