[Cinema-Spatial-Virtual]
# Using pipewire causes stalling
profile-desc="Force audio to 7.1 then convert to 3D Binaural Audio"
audio-channels=7.1
af=format=channels=7.1,lavfi=[surround:chl_out=7.1],lavfi=[bass=g=3]
