## Top-Level Defaults
## UI ##
fullscreen=yes                                                   #start on fullscreen
autofit=100%
## Audio  ##
volume-max=100						         #set max volume in %
volume=70                                                        #set volume on start
audio-channels=7.1                                               #force output to 8 channels
af=format=channels=7.1,lavfi=[surround],lavfi=[bass=g=3]         #use audio filter to process audio
## Video ##
dither-depth=auto
dither=fruit
temporal-dither=yes          		                         # Reduces visible dither patterns over time 
temporal-dither-period=1     		                         # Change pattern every frame (fastest cycling)
tone-mapping=spline
sigmoid-upscaling=yes				                 # Prevents ringing/aliasing artifacts during upscaling
linear-downscaling=yes
correct-downscaling=yes
target-colorspace-hint=auto
target-prim=auto
target-trc=auto
target-peak=auto
target-contrast=auto
gamut-mapping-mode=auto
deband=yes
deband-iterations=2
deband-threshold=35
deband-range=20
deband-grain=2
## Color ##
gamma=1.02
contrast=1.05
saturation=1.05
brightness=0.0
