### Profile ##
include="~~/audio.conf"
## Global Video ##
# Linux Profile as foundation
[Linux-Platform]
profile-cond=platform = "linux"
vo=gpu-next
gpu-api=vulkan,auto
gpu-context=auto
fbo-format=rgba16hf
hwdec=vulkan,auto

[default]
fullscreen=yes


