## Top-Level Defaults
## UI ##
fullscreen=yes                                                   #start on fullscreen
## Audio  ##
volume-max=100						         #set max volume in %
volume=70                                                        #set volume on start
audio-channels=7.1                                               #force output to 8 channels
af=format=channels=7.1,lavfi=[surround],lavfi=[bass=g=3]         #use audio filter to process audio

